### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#91]
Originally reported by: **Sébastien Celles (Bitbucket: [scls19fr](http://bitbucket.org/scls19fr), GitHub: [scls19fr](http://github.com/scls19fr))**

---

Hello,

it will be nice to add continuous integration to apscheduler project

Travis-CI can be set using a .travis.yml file that you put at project root like this
https://travis-ci.org/

```
#!yml

    language: python
    python:
      - "2.6"
      - "2.7"
      - "3.2"
      - "3.3"
      - "3.4"

    # command to install dependencies
    install:
      - "pip install ."

    # command to run tests
    script: nosetests
```

You can also add a badge using markdown syntax:

```
[![Build Status](https://travis-ci.org/username/project.svg?branch=master)](https://travis-ci.org/username/project)
```

Kind regards

---
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/91
